name: Get Flatfiles on a CRON Schedule

on:
  workflow_dispatch:
jobs:
  Download:
    name: Download
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Download
      uses: actions/download-sftp-files@v1
      with:
        host: ${{ secrets.FLATFILE_INTEGRATION_SERVER }}
        port: 22
        username: ${{ secrets.FLATFILE_INTEGRATION_USER }}
        password: ${{ secrets.FLATFILE_INTEGRATION_PASS }}
        remote-dir-path: '.'
        local-dir-path: ${{ github.workspace }}
        fail-if-no-files: 'true'
        
