name: Download File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download File
      run: |
        curl -u ${{ secrets.FLATFILE_INTEGRATION_USER }}:${{ secrets.FLATFILE_INTEGRATION_PASS }} ${{ secrets.FLATFILE_INTEGRATION_SERVER }} --output ./Availability-Pricing-GRC.json
        working-directory: ${{ github.workspace }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add Availability-Pricing-GRC.json
        git commit -m 'Update downloaded file'
        git push
