name: Get Flatfiles on a CRON Schedule

on:
  workflow_dispatch:
  
permissions:
  contents: write
 
jobs:
  sync-folder:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp
 
      - name: Add SFTP server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SFTP_HOST >> ~/.ssh/known_hosts
        env:
          SFTP_HOST: celestyaldataplatform.blob.core.windows.net
 
      - name: Download folder from SFTP
        run: |
          mkdir -p sftp_data
          lftp -u "celestyaldataplatform.godigitalpricing,SL5SSlL1J3YYuyb0rs0EeD8DYL2PTsTm" sftp://celestyaldataplatform.blob.core.windows.net <<EOF
          mirror --verbose --P . ./sftp_data
          bye
          EOF
        env:
          SFTP_HOST: celestyaldataplatform.blob.core.windows.net
 
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cp -r sftp_data/* .
          git add .
          git commit -m "Sync folder from SFTP server"
          git push
        continue-on-error: true
