name: Get Flatfiles on a CRON Schedule

on:
  workflow_dispatch:
jobs:
  sftp_transfer_job:
    runs-on: ubuntu-latest
    name: SFTP Transfer Test
    steps:
    - uses: actions/checkout@v2
   
    - name: Connect
      id: connect
      uses: danhendrickson/sftp-transfer-action@v1.23
      with:
        server: ${{ secrets.FLATFILE_INTEGRATION_SERVER }}
        user: ${{ secrets.FLATFILE_INTEGRATION_USER }}
        pass: ${{ secrets.FLATFILE_INTEGRATION_PASS }}
        port: 22
        local-path: './dist/'
        remote-path: '/public_html/test/'

    - name: Transfer Status
      run: echo "Transfer Status - ${{ steps.connect.outputs.transferStatus }}"
