name: Get Flatfiles on a CRON Schedule

on:
  workflow_dispatch:
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FLATFILE_INTEGRATION_SERVER }}
        ftp-username: ${{ secrets.FLATFILE_INTEGRATION_USER }}
        ftp-password: ${{ secrets.FLATFILE_INTEGRATION_PASS }}
        dry-run: true
    - name: Transfer Status
      run: echo "Transfer Status - ${{ steps.connect.outputs.transferStatus }}"
